output_dir: work_dirs
exp_name: speed_final

dataset:
  type: TrajectoryDatasetFullData
  target_columns:
    - speed
  train_bs: 256
  val_bs: 256
  val_metric: speed_mse

optimizer:
  type: Adam
  parameters:
    lr: 0.001

model:
  type: tft

pl_model:
  TrajectoryPredictorTFT

loss:
  type: MSELoss

train_params:
  n_epochs: 100
  device: gpu
